create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  admin_updated_at timestamptz,
  service_type text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'quoted', 'closed')),
  full_name text,
  company text,
  email text,
  whatsapp text,
  region text,
  client_type text,
  payload jsonb not null default '{}'::jsonb
);

alter table public.service_requests
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists admin_updated_at timestamptz,
  add column if not exists status text not null default 'new';

update public.service_requests
set status = 'new'
where status is null;

alter table public.service_requests
  drop constraint if exists service_requests_status_check;

alter table public.service_requests
  add constraint service_requests_status_check
  check (status in ('new', 'contacted', 'quoted', 'closed'));

create or replace function public.set_service_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_requests_set_updated_at on public.service_requests;

create trigger service_requests_set_updated_at
before update on public.service_requests
for each row
execute function public.set_service_requests_updated_at();

alter table public.service_requests enable row level security;

drop policy if exists "service_requests_public_insert" on public.service_requests;
create policy "service_requests_public_insert"
on public.service_requests
for insert
to anon, authenticated
with check (true);

drop policy if exists "service_requests_admin_select" on public.service_requests;
create policy "service_requests_admin_select"
on public.service_requests
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_requests_admin_update" on public.service_requests;
create policy "service_requests_admin_update"
on public.service_requests
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
