create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  admin_updated_at timestamptz,
  service_type text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'quoted', 'closed')),
  full_name text,
  company text,
  email text,
  whatsapp text,
  region text,
  client_type text,
  payload jsonb not null default '{}'::jsonb
);

alter table public.service_requests
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists admin_updated_at timestamptz,
  add column if not exists status text not null default 'new';

update public.service_requests
set status = 'new'
where status is null;

alter table public.service_requests
  drop constraint if exists service_requests_status_check;

alter table public.service_requests
  add constraint service_requests_status_check
  check (status in ('new', 'contacted', 'quoted', 'closed'));

create or replace function public.set_service_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_requests_set_updated_at on public.service_requests;

create trigger service_requests_set_updated_at
before update on public.service_requests
for each row
execute function public.set_service_requests_updated_at();

alter table public.service_requests enable row level security;

drop policy if exists "service_requests_public_insert" on public.service_requests;
create policy "service_requests_public_insert"
on public.service_requests
for insert
to anon, authenticated
with check (true);

drop policy if exists "service_requests_admin_select" on public.service_requests;
create policy "service_requests_admin_select"
on public.service_requests
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_requests_admin_update" on public.service_requests;
create policy "service_requests_admin_update"
on public.service_requests
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.customer_projects (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  request_id bigint references public.service_requests(id) on delete set null,
  name text not null,
  customer_name text,
  customer_email text,
  service_type text,
  summary text,
  status text not null default 'active' check (status in ('active', 'paused', 'completed', 'archived'))
);

create table if not exists public.project_timeline_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.customer_projects(id) on delete cascade,
  event_type text not null default 'update',
  title text not null,
  details text,
  event_at timestamptz not null default now()
);

create table if not exists public.project_notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.customer_projects(id) on delete cascade,
  channel text not null default 'email',
  recipient text,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamptz
);

create table if not exists public.project_invoices (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.customer_projects(id) on delete cascade,
  label text not null,
  amount numeric(12,2) not null default 0,
  currency text not null default 'USD',
  due_date date,
  status text not null default 'draft' check (status in ('draft', 'issued', 'paid', 'overdue')),
  sent_at timestamptz
);

create or replace function public.apply_project_invoice_status_rules()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'draft' and new.sent_at is not null then
    new.status = 'issued';
  end if;

  if new.status <> 'paid' and new.due_date is not null and new.due_date < current_date then
    new.status = 'overdue';
  end if;

  if new.status in ('issued', 'paid') and new.sent_at is null then
    new.sent_at = now();
  end if;

  if new.status = 'draft' then
    new.sent_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists project_invoices_apply_status_rules on public.project_invoices;

create trigger project_invoices_apply_status_rules
before insert or update on public.project_invoices
for each row
execute function public.apply_project_invoice_status_rules();

update public.project_invoices
set status = 'overdue'
where status in ('draft', 'issued')
  and due_date is not null
  and due_date < current_date;

create table if not exists public.project_deliverables (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.customer_projects(id) on delete cascade,
  title text not null,
  description text,
  due_date date,
  status text not null default 'queued' check (status in ('queued', 'in_progress', 'submitted', 'approved'))
);

create table if not exists public.project_approval_checkpoints (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  project_id bigint not null references public.customer_projects(id) on delete cascade,
  checkpoint text not null,
  owner text,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  approved_at timestamptz
);

create or replace function public.set_customer_projects_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists customer_projects_set_updated_at on public.customer_projects;

create trigger customer_projects_set_updated_at
before update on public.customer_projects
for each row
execute function public.set_customer_projects_updated_at();

alter table public.customer_projects enable row level security;
alter table public.project_timeline_events enable row level security;
alter table public.project_notifications enable row level security;
alter table public.project_invoices enable row level security;
alter table public.project_deliverables enable row level security;
alter table public.project_approval_checkpoints enable row level security;

drop policy if exists "customer_projects_admin_select" on public.customer_projects;
create policy "customer_projects_admin_select"
on public.customer_projects
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "customer_projects_admin_insert" on public.customer_projects;
create policy "customer_projects_admin_insert"
on public.customer_projects
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "customer_projects_admin_update" on public.customer_projects;
create policy "customer_projects_admin_update"
on public.customer_projects
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_timeline_admin_select" on public.project_timeline_events;
create policy "project_timeline_admin_select"
on public.project_timeline_events
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_timeline_admin_insert" on public.project_timeline_events;
create policy "project_timeline_admin_insert"
on public.project_timeline_events
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_timeline_admin_update" on public.project_timeline_events;
create policy "project_timeline_admin_update"
on public.project_timeline_events
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_notifications_admin_select" on public.project_notifications;
create policy "project_notifications_admin_select"
on public.project_notifications
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_notifications_admin_insert" on public.project_notifications;
create policy "project_notifications_admin_insert"
on public.project_notifications
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_notifications_admin_update" on public.project_notifications;
create policy "project_notifications_admin_update"
on public.project_notifications
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_invoices_admin_select" on public.project_invoices;
create policy "project_invoices_admin_select"
on public.project_invoices
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_invoices_admin_insert" on public.project_invoices;
create policy "project_invoices_admin_insert"
on public.project_invoices
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_invoices_admin_update" on public.project_invoices;
create policy "project_invoices_admin_update"
on public.project_invoices
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_deliverables_admin_select" on public.project_deliverables;
create policy "project_deliverables_admin_select"
on public.project_deliverables
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_deliverables_admin_insert" on public.project_deliverables;
create policy "project_deliverables_admin_insert"
on public.project_deliverables
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_deliverables_admin_update" on public.project_deliverables;
create policy "project_deliverables_admin_update"
on public.project_deliverables
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_checkpoints_admin_select" on public.project_approval_checkpoints;
create policy "project_checkpoints_admin_select"
on public.project_approval_checkpoints
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_checkpoints_admin_insert" on public.project_approval_checkpoints;
create policy "project_checkpoints_admin_insert"
on public.project_approval_checkpoints
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "project_checkpoints_admin_update" on public.project_approval_checkpoints;
create policy "project_checkpoints_admin_update"
on public.project_approval_checkpoints
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.service_request_estimates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  request_id bigint not null unique references public.service_requests(id) on delete cascade,
  rate_version text not null default 'mvp-v1',
  currency text not null default 'JMD',
  estimated_low numeric(12,2) not null default 0,
  estimated_target numeric(12,2) not null default 0,
  estimated_high numeric(12,2) not null default 0,
  confidence integer not null default 50 check (confidence between 0 and 100),
  client_budget_text text,
  client_budget_min numeric(12,2),
  client_budget_max numeric(12,2),
  variance_status text not null default 'unknown' check (variance_status in ('within', 'near', 'over', 'unknown')),
  variance_amount numeric(12,2),
  variance_percent numeric(8,2),
  estimate_payload jsonb not null default '{}'::jsonb
);

create index if not exists service_request_estimates_request_id_idx
  on public.service_request_estimates(request_id);

create or replace function public.set_service_request_estimates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_request_estimates_set_updated_at on public.service_request_estimates;

create trigger service_request_estimates_set_updated_at
before update on public.service_request_estimates
for each row
execute function public.set_service_request_estimates_updated_at();

alter table public.service_request_estimates enable row level security;

drop policy if exists "service_request_estimates_admin_select" on public.service_request_estimates;
create policy "service_request_estimates_admin_select"
on public.service_request_estimates
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_request_estimates_admin_insert" on public.service_request_estimates;
create policy "service_request_estimates_admin_insert"
on public.service_request_estimates
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_request_estimates_admin_update" on public.service_request_estimates;
create policy "service_request_estimates_admin_update"
on public.service_request_estimates
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.service_pricing_presets (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  service_type text not null unique check (service_type in ('website', 'software', 'discovery')),
  currency text not null default 'JMD',
  base_rate numeric(12,2) not null default 0,
  config jsonb not null default '{}'::jsonb
);

create or replace function public.set_service_pricing_presets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_pricing_presets_set_updated_at on public.service_pricing_presets;

create trigger service_pricing_presets_set_updated_at
before update on public.service_pricing_presets
for each row
execute function public.set_service_pricing_presets_updated_at();

alter table public.service_pricing_presets enable row level security;

drop policy if exists "service_pricing_presets_admin_select" on public.service_pricing_presets;
create policy "service_pricing_presets_admin_select"
on public.service_pricing_presets
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_pricing_presets_admin_insert" on public.service_pricing_presets;
create policy "service_pricing_presets_admin_insert"
on public.service_pricing_presets
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "service_pricing_presets_admin_update" on public.service_pricing_presets;
create policy "service_pricing_presets_admin_update"
on public.service_pricing_presets
for update
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.service_pricing_presets (service_type, currency, base_rate, config)
values
  (
    'website',
    'JMD',
    220000,
    jsonb_build_object(
      'featureUnit', 26000,
      'goalUnit', 12000,
      'customFeatures', 55000,
      'existingWebsite', 35000,
      'noDesignAssets', 45000,
      'references', 15000,
      'premiumDesign', 22000,
      'startupMultiplier', 0.95,
      'urgentMultiplier', 1.25,
      'acceleratedMultiplier', 1.1,
      'phasedMultiplier', 0.94,
      'lowMultiplier', 0.85,
      'highMultiplier', 1.25,
      'minimumTarget', 50000
    )
  ),
  (
    'software',
    'JMD',
    1400000,
    jsonb_build_object(
      'featureUnit', 95000,
      'roleUnit', 45000,
      'integrationUnit', 70000,
      'securityUnit', 55000,
      'apiDependency', 120000,
      'noDesignAssets', 140000,
      'enterpriseMultiplier', 1.2,
      'startupMultiplier', 0.95,
      'urgentMultiplier', 1.25,
      'acceleratedMultiplier', 1.1,
      'phasedMultiplier', 0.94,
      'lowMultiplier', 0.85,
      'highMultiplier', 1.25,
      'minimumTarget', 50000
    )
  ),
  (
    'discovery',
    'JMD',
    120000,
    jsonb_build_object(
      'summaryLargeContext', 35000,
      'softwareTrack', 25000,
      'startupMultiplier', 0.95,
      'urgentMultiplier', 1.25,
      'acceleratedMultiplier', 1.1,
      'phasedMultiplier', 0.94,
      'lowMultiplier', 0.85,
      'highMultiplier', 1.25,
      'minimumTarget', 50000
    )
  )
on conflict (service_type) do nothing;

-- ============================================================
-- Client portal: additional columns on customer_projects
-- ============================================================

alter table public.customer_projects
  add column if not exists progress integer not null default 0 check (progress between 0 and 100),
  add column if not exists current_phase text,
  add column if not exists contract_value numeric(12,2),
  add column if not exists currency text not null default 'USD',
  add column if not exists next_action text;

-- ============================================================
-- Client portal: is_customer_visible flag on timeline events
-- ============================================================

alter table public.project_timeline_events
  add column if not exists is_customer_visible boolean not null default false;

-- ============================================================
-- Client portal: RLS policies (read-only, own data only)
-- ============================================================

-- Clients can read their own service requests (matched by email)
drop policy if exists "service_requests_client_select" on public.service_requests;
create policy "service_requests_client_select"
on public.service_requests
for select
to authenticated
using (
  email = (auth.jwt() ->> 'email')
  and (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin'
);

-- Clients can read their own projects (matched by customer_email)
drop policy if exists "customer_projects_client_select" on public.customer_projects;
create policy "customer_projects_client_select"
on public.customer_projects
for select
to authenticated
using (
  customer_email = (auth.jwt() ->> 'email')
  and (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin'
);

-- Clients can read deliverables for their own projects
drop policy if exists "project_deliverables_client_select" on public.project_deliverables;
create policy "project_deliverables_client_select"
on public.project_deliverables
for select
to authenticated
using (
  (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin'
  and project_id in (
    select id from public.customer_projects
    where customer_email = (auth.jwt() ->> 'email')
  )
);

-- Clients can read customer-visible timeline events for their own projects
drop policy if exists "project_timeline_client_select" on public.project_timeline_events;
create policy "project_timeline_client_select"
on public.project_timeline_events
for select
to authenticated
using (
  is_customer_visible = true
  and (auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin'
  and project_id in (
    select id from public.customer_projects
    where customer_email = (auth.jwt() ->> 'email')
  )
);
